[build-system]
requires = [
  "setuptools>=61.0",
  "APScheduler==3.8.1",
  "dicttoxml==1.7.4",
  "Flask==2.0.2",
  "jsonschema==4.2.1",
  "pandas==1.3.4",
  "pycodestyle==2.8.0",
  "PyYAML==6.0",
  "requests==2.26.0",
  "tzlocal==4.1",
  "urllib3==1.26.7"
]
build-backend = "setuptools.build_meta"

[project]
name = "INF5190-H22"
version = "0.0.1"
authors = [
  { name="Hussein Nahle", email="hussein-188@hotmail.com" },
]
description = "Travail pratique API"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/husseinnahle/INF5190-H22"
"Bug Tracker" = "https://github.com/husseinnahle/INF5190-H22/issues"
