resources:
- name: repo
  type: git
  source:
    uri: https://github.com/husseinnahle/INF5190-H22
    branch: ci_pipeline

jobs:
- name: test
  plan:
  - get: repo
    trigger: true
  - task: set-pipeline
    file: repo/ci/set_pipelines.yml
    input_mapping:
      repo: repo
