jobs:
- name: test
  plan:
  - task: test
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: /bin/sh
        args:
          - -xce
          - |
            echo "test ((number))"