resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: aoldershaw/github-pr-resource

resources:
- name: pull-requests
  type: pull-request
  check_every: 24h
  webhook_token: ((pr-webhook-token))
  source:
    repository: husseinnahle/INF5190-H22
    access_token: ((github-access-token))

- name: repo
  type: git
  source:
    uri: https://github.com/husseinnahle/INF5190-H22
    branch: ci_pipeline

jobs:
- name: test
  plan:
  - get: repo
  - get: pull-requests
    trigger: true
  - load_var: pull_requests
    file: pull-requests/prs.json
  - across:
    - var: pr
      values: ((.:pull_requests))
    set_pipeline: prs
    file: repo/ci/template.yml
    instance_vars: {number: ((.:pr.number))}