resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: tasruntime/github-pr-resource

resources:
- name: pull-requests
  type: pull-request
  source:
    repository: husseinnahle/INF5190-H22
    branch: ci_pipeline

- name: ci
  type: git
  source:
    uri: https://github.com/concourse/ci

jobs:
- name: update-pr-pipelines
  plan:
  - get: ci
  - get: pull-requests
    trigger: true
  - load_var: pull_requests
    file: pull-requests/prs.json
  - across:
    - var: pr
      values: ((.:pull_requests))
    set_pipeline: prs
    file: ci/pipelines/child.yml
    instance_vars: {number: ((.:pr.number))}